### ISSUE TITLE
请问有镜像下载地址吗

### ISSUE THREAD

**Issue by ghost** [a13134455667/HP-15-ax015TX-MAC10.15.4-OC-EFI#1]
你好，能否给个OS的镜像下载地址，谢谢。

**Comment by a13134455667** [comment]
远景论坛上有。



---原始邮件---
发件人: "Marco"<notifications@github.com&gt;
发送时间: 2020年6月25日(周四) 晚上6:04
收件人: "a13134455667/HP-15-ax015TX-MAC10.15.4-OC-EFI"<HP-15-ax015TX-MAC10.15.4-OC-EFI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [a13134455667/HP-15-ax015TX-MAC10.15.4-OC-EFI] 请问有镜像下载地址吗 (#1)




 
你好，能否给个OS的镜像下载地址，谢谢。

**Comment by ghost** [comment]
好的
