### ISSUE TITLE
关于无法外接显示器的问题

### ISSUE THREAD

**Issue by zequn12** [a13134455667/HP-15-ax015TX-MAC10.15.4-OC-EFI#4]
首先感谢大佬的分享，已经成功的安装了黑苹果。笔记本上使用很完美，目前发现的问题是HDMI外接显示器无法亮屏，不知道是我的个例还是普遍的问题

**Comment by a13134455667** [comment]
由HDMI接口是通过独立显卡输出，所以无法驱动独立显卡就无法使用HDMI外接显示器



---原始邮件---
发件人: "Zequn Yang"<notifications@github.com&gt;
发送时间: 2020年8月23日(周日) 晚上7:22
收件人: "a13134455667/HP-15-ax015TX-MAC10.15.4-OC-EFI"<HP-15-ax015TX-MAC10.15.4-OC-EFI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [a13134455667/HP-15-ax015TX-MAC10.15.4-OC-EFI] 关于无法外接显示器的问题 (#4)




 
首先感谢大佬的分享，已经成功的安装了黑苹果。笔记本上使用很完美，目前发现的问题是HDMI外接显示器无法亮屏，不知道是我的个例还是普遍的问题

**Comment by zequn12** [comment]
ok 明白了
